Make 10.5.10 work and fix some issues
* Repair symlinks from old executables to new executables added
  in 10.5. Allows using 10.5 and later in mariadb4j-core.
* Update groupId since this is a fork
* Add Automatic-Module-Name to mariadb4j-core
* Require JDK 16
* Fix NoClassDefFoundError caused by shutdown hook
* Remove unneeded spring classes